service: tourist-travel-backend

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
  - serverless-cloudformation-changesets-v3

custom:
  resourcePolicies:
    lambdaAgentPolicy:
        - Effect: Allow
          Principal: "bedrock.amazonaws.com"
          Action: lambda:invokeFunction
          Resource:
            - !GetAtt agentTool.Arn
          Condition:
            ArnLike:
              aws:SourceArn: "YOUR_AGENT_ARN"


provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: "developer"
  stackName: "travel-tourist-api-stack"
  tracing:
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::<BUCKET_NAME>"
            - "arn:aws:s3:::<BUCKET_NAME>/*"

functions:
  agentTool:
    handler: src/Handlers/Agent.handler
    timeout: 900
    environment:
      BUCKET: "<BUCKET_NAME>"



